### ISSUE TITLE
Scooter - code review

### ISSUE THREAD

**Issue by mandyWW** [AyishaAlli/Multiverse-Bootcamp#3]
Really great job Ayisha! Love the fact you have paid attention to requirements and listed them in the README.

A few comments below:

**Diagrams**
- Use Case diagram - excellent level of detail, really impressed!
- Class diagram - label the relationships to make it easier to understand how classes are related
- Sequence diagram - LOVE the use of colour/alt flows, really good level of detail

**Code**
- Admin - ensure all methods start with a lowerCase
- Scooter - can you spot the mistake on line 29?! Think about assignment versus comparison.
- Maintenance - answer to how do you delete - see https://love2dev.com/blog/javascript-remove-from-array/
- RegisteredCustomer - instead of push on PaymentMethod you should call methods to set the value on the PaymentMethod (ping me on Slack to discuss more)

**Tests**
- nice use of when/then
- really well structured/named & comprehensive

TODO - add a coverage report

**Comment by AyishaAlli** [comment]
Hi Mandy, 

Thank you for all the comments.

- I have added labels on my class diagram 
- I have edited the variable name on admin.js 
- for line 29 i changed (scooter.range = 32) to (scooter.range === 32), I think that is the mistake? i also then had to change scooter.range to 'this.range' so it is now (this.range === 32)
-I used the method pop() meaning the employee would have to finish the job and mark it complete before moving on to the next job. 
- i made RegisteredCustomer's property 'PaymentDetails' an Object,  then set the value equal to the given params in the function 'addpaymentDetails()' . if thats what you mean? - yes can discuss further on slack
- I have now added a pic of the coverage report 
Thank you very much! :D
